# Generated by Django 4.0.6 on 2022-10-01 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkmnow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHashData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('git_hash', models.CharField(max_length=200)),
            ],
        ),
    ]
